### PR TITLE
fix: Drift not hiding if shown when destroyed

### LINKED ISSUE #60: Properly destroying Drift
I'm trying to get Drift to work with Ember and am having some success.   Since there aren't any page reloads I want to be sure that I am cleaning up all remnants of Drift on transition out of the route that uses it.

Right now I'm doing this:

```
let drift = New Drift(...);
...
destroyMethod() {
    drift.destroy();
    window.Drift = null;
    drift = null;
}
```

And that seems to work, but is there anything else I need to address?  Perhaps some DOM elements that could potentially be left hanging around?

Thanks for this plugin - I love it!

### PR DESCRIPTION
**Pull request by vetruvet**
Breaking change?: *NO*
Fixes #60 

## Description

If Drift is shown when `destroy` is called, the events get unbound but elements don't get hidden. This results in unresponsive visual elements that hang around.

This fixes the issue by calling `_hide` on the trigger object.

## Checklist

- [x] All existing unit tests are still passing (if applicable)
- [x] Add new passing unit tests to cover the code introduced by your PR
- [ ] Update the readme _(n/a?)_
- [ ] Update or add any necessary API documentation  _(n/a?)_
- [x] Add some [steps](#steps-to-test) so we can test your bug fix
- [ ] The PR title is in the [conventional commit](#conventional-commit-spec) format: e.g. `fix(<area>): fixed bug #issue-number`
- [ ] Add your info to the [contributors](#packagejson-contributors) array in package.json!

## Steps to Test

1. Set up Drift
2. Hover over target element
3. Call `destroy` (e.g. on a `setTimeout` for testing)
4. See that Drift's elements are hidden properly.

### CODE REVIEW

File: test/testDrift.js [hunk 1]
```diff
@@ -137,5 +137,20 @@ describe("Drift", () => {
         expect(drift.trigger.enabled).toBe(false);
       });
     });
+
+    describe("#destroy", () => {
+      it("should hide and unbind events", function() {
+        const anchor = document.querySelector(".test-anchor");
+        const drift = new Drift(anchor);
+
+        const hideSpy = spyOn(drift.trigger, "_hide");
```
Comment (sherwinski) [inline test/testDrift.js]: Looks like eslint doesn't recognize `spyOn` here, causing the tests to break. A quick search online shows that we should add (I assume) Jasmine to `.eslintrc.json` to fix this.
https://github.com/eslint/eslint/issues/1176#issuecomment-342004125

[travis results](https://travis-ci.org/imgix/drift/jobs/563340394) for reference

Comment (sherwinski) [reply test/testDrift.js]: Looks like all we actually needed was to add `spyOn` as an eslint global.

**Comment by vetruvet** [comment]
Thanks for the linter fix @sherwinski. My bad for for not checking lint first.

Though, I would say an easier and more sustainable way would be to add an `.eslintrc.json` file to the test directory and specify `{ "env": { "jasmine": true } }` in there. That way you would not need to manage the globals list at the top of each file. If you would like, I can make a separate PR with this change.

**Comment by sherwinski** [comment]
@vetruvet no problem! And totally agree with your suggestion, I would gladly take a PR for that. Thanks
